{{- $chart := include "chart" . -}}
{{- $fullname := include "fullname" . -}}
{{- $api := .Values.backend.api -}}
{{- $name := include "apiServiceName" . -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ $chart }}
    {{- if $api.additionalLabels}}
    {{- toYaml $api.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  type: {{ $api.service.type }}
  ports:
    - port: {{ $api.service.exposedPort }}
      targetPort: {{ $api.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
