{{- $fullname := include "fullname" . -}}
{{- $dashboard := .Values.dashboard -}}
{{- $name := printf "%s-dashboard" $fullname -}}
{{- $chart := include "chart" . -}}

{{- if $dashboard.autoscaler.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ $chart }}
    {{- if $dashboard.additionalLabels}}
    {{- toYaml $dashboard.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  minReplicas: {{ default $dashboard.autoscaler.minReplicas $dashboard.autoscaler.minReplicas }}
  maxReplicas: {{ default 3 $dashboard.autoscaler.maxReplicas }}

  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization:  {{ default 70 $dashboard.autoscaler.targetCPUUtil }}

---
{{- end }}