{{- $fullname := include "fullname" . -}}
{{- $dashboard := .Values.dashboard -}}
{{- $name := printf "%s-dashboard" $fullname -}}
{{- $chart := include "chart" . -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ $chart }}
    {{- if $dashboard.additionalLabels}}
    {{- toYaml $dashboard.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  type: {{ $dashboard.service.type }}
  ports:
    - port: {{ $dashboard.service.exposedPort }}
      targetPort: {{ $dashboard.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
