{{- $fullname := include "fullname" . -}}
{{- $dashboard := .Values.dashboard -}}
{{- $api := .Values.backend.api -}}
{{- $apiServiceName := include "apiServiceName" . -}}
{{- $name := printf "%s-dashboard-nginx" $fullname -}}
{{- $chart := include "chart" . -}}


apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ $chart }}
    {{- if $dashboard.additionalLabels}}
{{ toYaml $dashboard.additionalLabels | nindent 4 }}
    {{- end }}
data:
  default.conf: |
    server { 
      listen 8080; 
      server_name localhost; 
      location / { 
          root /usr/share/nginx/html; 
          index index.html index.htm; 
          try_files $uri $uri/ /index.html; 
      }
      location {{ $api.ingress.path }} {
        if ($request_method = 'OPTIONS') {
          add_header 'Access-Control-Allow-Origin' {{ $api.ingress.host }};
          add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS,PUT,DELETE,PATCH';
          add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
          add_header 'Access-Control-Max-Age' 1728000;
          add_header 'Content-Type' 'text/plain; charset=utf-8';
          add_header 'Content-Length' 0;
          return 204;
        }
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
        add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS,PUT,DELETE,PATCH';
        proxy_hide_header 'Access-Control-Allow-Origin';
        proxy_ssl_server_name off;
        proxy_pass http://{{ $apiServiceName }}:{{ $api.service.exposedPort }}{{ $api.ingress.path }};
        proxy_set_header Accept-Encoding "";
        add_header 'Access-Control-Allow-Origin' * always;
      }
      error_page 500 502 503 504 /50x.html; 
      location = /50x.html { 
          root /usr/share/nginx/html; 
      } 
    }