{{- $chart := include "chart" . -}}
{{- $fullname := include "fullname" . -}}
{{- $tracker := .Values.backend.tracker -}}
{{- $backend := .Values.backend -}}
{{- $name := printf "%s-tracker" $fullname -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ $chart }}
    {{- if $tracker.additionalLabels}}
{{ toYaml $tracker.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/managed-by: {{ $.Release.Service }}
        helm.sh/chart: {{ $chart }}
        {{- if $tracker.additionalLabels}}
{{ toYaml $tracker.additionalLabels | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 1001
      containers:
        - name: tracker
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1001
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          image: "{{ $backend.image.registry }}/{{ $backend.image.repository }}:{{ $backend.image.tag }}"
          imagePullPolicy: {{ $backend.image.pullPolicy }}
          {{- if $tracker.command }}
          command: [{{ $tracker.command }}]
          {{- if $tracker.args }}
          args: {{- range $tracker.args }}
            - {{.}}
            {{- end }}
          {{- end }}
          {{- end }}
          env:
            - name: VERBOSITY
              value: {{ $backend.verbosity }}
            - name: ALCHEMY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "alchemySecretName" . }}
                  key: {{ $.Values.global.alchemy.apiKeySecretKey }}
            - name: INITIAL_ADMIN_ADDRESS
              value: {{ $.Values.global.initialAdminAddress | quote }}
            {{- if $.Values.global.rpcURL }}
            - name: RPC_URL
              value: {{ $.Values.global.rpcURL | quote }}
            {{- end }}
            - name: DBHOST
              value: {{ include "postgresHost" . | quote}}
            - name: DBPORT
              value: {{ include "postgresPort" . | quote }}
            - name: DBNAME
              value: {{ include "postgresDatabase" . }}
            - name: DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresPasswordSecret" . | quote}}
                  key: {{ include "postgresPasswordKey" . | quote}}
            - name: DBUSER
              {{- if .Values.postgresql.enabled }}
              {{- if .Values.postgresql.auth.username }}
              value: {{ .Values.postgresql.auth.username | quote }}
              {{- else }}
              value: {{ "postgres" | quote }}
              {{- end }}

              {{- else }}

              {{- if not .Values.externalPostgresql.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresPasswordSecret" . }}
                  key: {{ .Values.externalPostgresql.secretKeys.usernameKey }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalPostgresql.existingSecret }}
                  key: {{ .Values.externalPostgresql.secretKeys.usernameKey }}
              {{- end }}
              {{- end }}

          {{- if $tracker.env }}
          {{- toYaml $tracker.env | indent 12 }}
          {{- end }}
          resources:
            {{- toYaml $tracker.resources | nindent 14 }}
