/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GrantRouteImport } from './routes/grant'
import { Route as ExpenseRouteImport } from './routes/expense'
import { Route as R404RouteImport } from './routes/$404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GrantIndexRouteImport } from './routes/grant/index'
import { Route as ExpenseIndexRouteImport } from './routes/expense/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TransferTransferIdRouteImport } from './routes/transfer/$transferId'
import { Route as GrantGrantIdRouteImport } from './routes/grant/$grantId'
import { Route as ExpenseExpenseIdRouteImport } from './routes/expense/$expenseId'
import { Route as AdminWalletsRouteImport } from './routes/admin/wallets'
import { Route as AdminTransfersRouteImport } from './routes/admin/transfers'
import { Route as AdminOrganizationRouteImport } from './routes/admin/organization'
import { Route as AdminGrantsRouteImport } from './routes/admin/grants'
import { Route as AdminExpensesRouteImport } from './routes/admin/expenses'
import { Route as AdminBudgetsRouteImport } from './routes/admin/budgets'
import { Route as AdminAuditLogRouteImport } from './routes/admin/audit-log'
import { Route as AdminAdminsRouteImport } from './routes/admin/admins'
import { Route as AdminAddAssetRouteImport } from './routes/admin/add-asset'
import { Route as AdminAddAdminRouteImport } from './routes/admin/add-admin'
import { Route as Admin_layoutRouteImport } from './routes/admin/__layout'
import { Route as AdminGrantsIndexRouteImport } from './routes/admin/grants/index'
import { Route as AdminExpensesIndexRouteImport } from './routes/admin/expenses/index'
import { Route as AdminGrantsGrantIdRouteImport } from './routes/admin/grants/$grantId'
import { Route as AdminExpensesExpenseIdRouteImport } from './routes/admin/expenses/$expenseId'
import { Route as AdminGrantsGrantIdIndexRouteImport } from './routes/admin/grants/$grantId/index'
import { Route as AdminGrantsGrantIdMilestonesRouteImport } from './routes/admin/grants/$grantId/milestones'
import { Route as AdminGrantsGrantIdFundsUsageRouteImport } from './routes/admin/grants/$grantId/funds-usage'
import { Route as AdminGrantsGrantIdDisbursementsRouteImport } from './routes/admin/grants/$grantId/disbursements'

const AdminRouteImport = createFileRoute('/admin')()

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantRoute = GrantRouteImport.update({
  id: '/grant',
  path: '/grant',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseRoute = ExpenseRouteImport.update({
  id: '/expense',
  path: '/expense',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/$404',
  path: '/$404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantIndexRoute = GrantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GrantRoute,
} as any)
const ExpenseIndexRoute = ExpenseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExpenseRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TransferTransferIdRoute = TransferTransferIdRouteImport.update({
  id: '/transfer/$transferId',
  path: '/transfer/$transferId',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantGrantIdRoute = GrantGrantIdRouteImport.update({
  id: '/$grantId',
  path: '/$grantId',
  getParentRoute: () => GrantRoute,
} as any)
const ExpenseExpenseIdRoute = ExpenseExpenseIdRouteImport.update({
  id: '/$expenseId',
  path: '/$expenseId',
  getParentRoute: () => ExpenseRoute,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransfersRoute = AdminTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationRoute = AdminOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGrantsRoute = AdminGrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExpensesRoute = AdminExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBudgetsRoute = AdminBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAddAssetRoute = AdminAddAssetRouteImport.update({
  id: '/add-asset',
  path: '/add-asset',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAddAdminRoute = AdminAddAdminRouteImport.update({
  id: '/add-admin',
  path: '/add-admin',
  getParentRoute: () => AdminRoute,
} as any)
const Admin_layoutRoute = Admin_layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGrantsIndexRoute = AdminGrantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminGrantsRoute,
} as any)
const AdminExpensesIndexRoute = AdminExpensesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminExpensesRoute,
} as any)
const AdminGrantsGrantIdRoute = AdminGrantsGrantIdRouteImport.update({
  id: '/$grantId',
  path: '/$grantId',
  getParentRoute: () => AdminGrantsRoute,
} as any)
const AdminExpensesExpenseIdRoute = AdminExpensesExpenseIdRouteImport.update({
  id: '/$expenseId',
  path: '/$expenseId',
  getParentRoute: () => AdminExpensesRoute,
} as any)
const AdminGrantsGrantIdIndexRoute = AdminGrantsGrantIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminGrantsGrantIdRoute,
} as any)
const AdminGrantsGrantIdMilestonesRoute =
  AdminGrantsGrantIdMilestonesRouteImport.update({
    id: '/milestones',
    path: '/milestones',
    getParentRoute: () => AdminGrantsGrantIdRoute,
  } as any)
const AdminGrantsGrantIdFundsUsageRoute =
  AdminGrantsGrantIdFundsUsageRouteImport.update({
    id: '/funds-usage',
    path: '/funds-usage',
    getParentRoute: () => AdminGrantsGrantIdRoute,
  } as any)
const AdminGrantsGrantIdDisbursementsRoute =
  AdminGrantsGrantIdDisbursementsRouteImport.update({
    id: '/disbursements',
    path: '/disbursements',
    getParentRoute: () => AdminGrantsGrantIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$404': typeof R404Route
  '/expense': typeof ExpenseRouteWithChildren
  '/grant': typeof GrantRouteWithChildren
  '/login': typeof LoginRoute
  '/transfers': typeof TransfersRoute
  '/admin': typeof Admin_layoutRoute
  '/admin/add-admin': typeof AdminAddAdminRoute
  '/admin/add-asset': typeof AdminAddAssetRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/budgets': typeof AdminBudgetsRoute
  '/admin/expenses': typeof AdminExpensesRouteWithChildren
  '/admin/grants': typeof AdminGrantsRouteWithChildren
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/expense/$expenseId': typeof ExpenseExpenseIdRoute
  '/grant/$grantId': typeof GrantGrantIdRoute
  '/transfer/$transferId': typeof TransferTransferIdRoute
  '/admin/': typeof AdminIndexRoute
  '/expense/': typeof ExpenseIndexRoute
  '/grant/': typeof GrantIndexRoute
  '/admin/expenses/$expenseId': typeof AdminExpensesExpenseIdRoute
  '/admin/grants/$grantId': typeof AdminGrantsGrantIdRouteWithChildren
  '/admin/expenses/': typeof AdminExpensesIndexRoute
  '/admin/grants/': typeof AdminGrantsIndexRoute
  '/admin/grants/$grantId/disbursements': typeof AdminGrantsGrantIdDisbursementsRoute
  '/admin/grants/$grantId/funds-usage': typeof AdminGrantsGrantIdFundsUsageRoute
  '/admin/grants/$grantId/milestones': typeof AdminGrantsGrantIdMilestonesRoute
  '/admin/grants/$grantId/': typeof AdminGrantsGrantIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$404': typeof R404Route
  '/login': typeof LoginRoute
  '/transfers': typeof TransfersRoute
  '/admin': typeof AdminIndexRoute
  '/admin/add-admin': typeof AdminAddAdminRoute
  '/admin/add-asset': typeof AdminAddAssetRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/budgets': typeof AdminBudgetsRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/expense/$expenseId': typeof ExpenseExpenseIdRoute
  '/grant/$grantId': typeof GrantGrantIdRoute
  '/transfer/$transferId': typeof TransferTransferIdRoute
  '/expense': typeof ExpenseIndexRoute
  '/grant': typeof GrantIndexRoute
  '/admin/expenses/$expenseId': typeof AdminExpensesExpenseIdRoute
  '/admin/expenses': typeof AdminExpensesIndexRoute
  '/admin/grants': typeof AdminGrantsIndexRoute
  '/admin/grants/$grantId/disbursements': typeof AdminGrantsGrantIdDisbursementsRoute
  '/admin/grants/$grantId/funds-usage': typeof AdminGrantsGrantIdFundsUsageRoute
  '/admin/grants/$grantId/milestones': typeof AdminGrantsGrantIdMilestonesRoute
  '/admin/grants/$grantId': typeof AdminGrantsGrantIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$404': typeof R404Route
  '/expense': typeof ExpenseRouteWithChildren
  '/grant': typeof GrantRouteWithChildren
  '/login': typeof LoginRoute
  '/transfers': typeof TransfersRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/__layout': typeof Admin_layoutRoute
  '/admin/add-admin': typeof AdminAddAdminRoute
  '/admin/add-asset': typeof AdminAddAssetRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/budgets': typeof AdminBudgetsRoute
  '/admin/expenses': typeof AdminExpensesRouteWithChildren
  '/admin/grants': typeof AdminGrantsRouteWithChildren
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/expense/$expenseId': typeof ExpenseExpenseIdRoute
  '/grant/$grantId': typeof GrantGrantIdRoute
  '/transfer/$transferId': typeof TransferTransferIdRoute
  '/admin/': typeof AdminIndexRoute
  '/expense/': typeof ExpenseIndexRoute
  '/grant/': typeof GrantIndexRoute
  '/admin/expenses/$expenseId': typeof AdminExpensesExpenseIdRoute
  '/admin/grants/$grantId': typeof AdminGrantsGrantIdRouteWithChildren
  '/admin/expenses/': typeof AdminExpensesIndexRoute
  '/admin/grants/': typeof AdminGrantsIndexRoute
  '/admin/grants/$grantId/disbursements': typeof AdminGrantsGrantIdDisbursementsRoute
  '/admin/grants/$grantId/funds-usage': typeof AdminGrantsGrantIdFundsUsageRoute
  '/admin/grants/$grantId/milestones': typeof AdminGrantsGrantIdMilestonesRoute
  '/admin/grants/$grantId/': typeof AdminGrantsGrantIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$404'
    | '/expense'
    | '/grant'
    | '/login'
    | '/transfers'
    | '/admin'
    | '/admin/add-admin'
    | '/admin/add-asset'
    | '/admin/admins'
    | '/admin/audit-log'
    | '/admin/budgets'
    | '/admin/expenses'
    | '/admin/grants'
    | '/admin/organization'
    | '/admin/transfers'
    | '/admin/wallets'
    | '/expense/$expenseId'
    | '/grant/$grantId'
    | '/transfer/$transferId'
    | '/admin/'
    | '/expense/'
    | '/grant/'
    | '/admin/expenses/$expenseId'
    | '/admin/grants/$grantId'
    | '/admin/expenses/'
    | '/admin/grants/'
    | '/admin/grants/$grantId/disbursements'
    | '/admin/grants/$grantId/funds-usage'
    | '/admin/grants/$grantId/milestones'
    | '/admin/grants/$grantId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$404'
    | '/login'
    | '/transfers'
    | '/admin'
    | '/admin/add-admin'
    | '/admin/add-asset'
    | '/admin/admins'
    | '/admin/audit-log'
    | '/admin/budgets'
    | '/admin/organization'
    | '/admin/transfers'
    | '/admin/wallets'
    | '/expense/$expenseId'
    | '/grant/$grantId'
    | '/transfer/$transferId'
    | '/expense'
    | '/grant'
    | '/admin/expenses/$expenseId'
    | '/admin/expenses'
    | '/admin/grants'
    | '/admin/grants/$grantId/disbursements'
    | '/admin/grants/$grantId/funds-usage'
    | '/admin/grants/$grantId/milestones'
    | '/admin/grants/$grantId'
  id:
    | '__root__'
    | '/'
    | '/$404'
    | '/expense'
    | '/grant'
    | '/login'
    | '/transfers'
    | '/admin'
    | '/admin/__layout'
    | '/admin/add-admin'
    | '/admin/add-asset'
    | '/admin/admins'
    | '/admin/audit-log'
    | '/admin/budgets'
    | '/admin/expenses'
    | '/admin/grants'
    | '/admin/organization'
    | '/admin/transfers'
    | '/admin/wallets'
    | '/expense/$expenseId'
    | '/grant/$grantId'
    | '/transfer/$transferId'
    | '/admin/'
    | '/expense/'
    | '/grant/'
    | '/admin/expenses/$expenseId'
    | '/admin/grants/$grantId'
    | '/admin/expenses/'
    | '/admin/grants/'
    | '/admin/grants/$grantId/disbursements'
    | '/admin/grants/$grantId/funds-usage'
    | '/admin/grants/$grantId/milestones'
    | '/admin/grants/$grantId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  ExpenseRoute: typeof ExpenseRouteWithChildren
  GrantRoute: typeof GrantRouteWithChildren
  LoginRoute: typeof LoginRoute
  TransfersRoute: typeof TransfersRoute
  AdminRoute: typeof AdminRouteWithChildren
  TransferTransferIdRoute: typeof TransferTransferIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grant': {
      id: '/grant'
      path: '/grant'
      fullPath: '/grant'
      preLoaderRoute: typeof GrantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense': {
      id: '/expense'
      path: '/expense'
      fullPath: '/expense'
      preLoaderRoute: typeof ExpenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$404': {
      id: '/$404'
      path: '/$404'
      fullPath: '/$404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grant/': {
      id: '/grant/'
      path: '/'
      fullPath: '/grant/'
      preLoaderRoute: typeof GrantIndexRouteImport
      parentRoute: typeof GrantRoute
    }
    '/expense/': {
      id: '/expense/'
      path: '/'
      fullPath: '/expense/'
      preLoaderRoute: typeof ExpenseIndexRouteImport
      parentRoute: typeof ExpenseRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/transfer/$transferId': {
      id: '/transfer/$transferId'
      path: '/transfer/$transferId'
      fullPath: '/transfer/$transferId'
      preLoaderRoute: typeof TransferTransferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grant/$grantId': {
      id: '/grant/$grantId'
      path: '/$grantId'
      fullPath: '/grant/$grantId'
      preLoaderRoute: typeof GrantGrantIdRouteImport
      parentRoute: typeof GrantRoute
    }
    '/expense/$expenseId': {
      id: '/expense/$expenseId'
      path: '/$expenseId'
      fullPath: '/expense/$expenseId'
      preLoaderRoute: typeof ExpenseExpenseIdRouteImport
      parentRoute: typeof ExpenseRoute
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transfers': {
      id: '/admin/transfers'
      path: '/transfers'
      fullPath: '/admin/transfers'
      preLoaderRoute: typeof AdminTransfersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organization': {
      id: '/admin/organization'
      path: '/organization'
      fullPath: '/admin/organization'
      preLoaderRoute: typeof AdminOrganizationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/grants': {
      id: '/admin/grants'
      path: '/grants'
      fullPath: '/admin/grants'
      preLoaderRoute: typeof AdminGrantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/expenses': {
      id: '/admin/expenses'
      path: '/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AdminExpensesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/budgets': {
      id: '/admin/budgets'
      path: '/budgets'
      fullPath: '/admin/budgets'
      preLoaderRoute: typeof AdminBudgetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/add-asset': {
      id: '/admin/add-asset'
      path: '/add-asset'
      fullPath: '/admin/add-asset'
      preLoaderRoute: typeof AdminAddAssetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/add-admin': {
      id: '/admin/add-admin'
      path: '/add-admin'
      fullPath: '/admin/add-admin'
      preLoaderRoute: typeof AdminAddAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/__layout': {
      id: '/admin/__layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof Admin_layoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/grants/': {
      id: '/admin/grants/'
      path: '/'
      fullPath: '/admin/grants/'
      preLoaderRoute: typeof AdminGrantsIndexRouteImport
      parentRoute: typeof AdminGrantsRoute
    }
    '/admin/expenses/': {
      id: '/admin/expenses/'
      path: '/'
      fullPath: '/admin/expenses/'
      preLoaderRoute: typeof AdminExpensesIndexRouteImport
      parentRoute: typeof AdminExpensesRoute
    }
    '/admin/grants/$grantId': {
      id: '/admin/grants/$grantId'
      path: '/$grantId'
      fullPath: '/admin/grants/$grantId'
      preLoaderRoute: typeof AdminGrantsGrantIdRouteImport
      parentRoute: typeof AdminGrantsRoute
    }
    '/admin/expenses/$expenseId': {
      id: '/admin/expenses/$expenseId'
      path: '/$expenseId'
      fullPath: '/admin/expenses/$expenseId'
      preLoaderRoute: typeof AdminExpensesExpenseIdRouteImport
      parentRoute: typeof AdminExpensesRoute
    }
    '/admin/grants/$grantId/': {
      id: '/admin/grants/$grantId/'
      path: '/'
      fullPath: '/admin/grants/$grantId/'
      preLoaderRoute: typeof AdminGrantsGrantIdIndexRouteImport
      parentRoute: typeof AdminGrantsGrantIdRoute
    }
    '/admin/grants/$grantId/milestones': {
      id: '/admin/grants/$grantId/milestones'
      path: '/milestones'
      fullPath: '/admin/grants/$grantId/milestones'
      preLoaderRoute: typeof AdminGrantsGrantIdMilestonesRouteImport
      parentRoute: typeof AdminGrantsGrantIdRoute
    }
    '/admin/grants/$grantId/funds-usage': {
      id: '/admin/grants/$grantId/funds-usage'
      path: '/funds-usage'
      fullPath: '/admin/grants/$grantId/funds-usage'
      preLoaderRoute: typeof AdminGrantsGrantIdFundsUsageRouteImport
      parentRoute: typeof AdminGrantsGrantIdRoute
    }
    '/admin/grants/$grantId/disbursements': {
      id: '/admin/grants/$grantId/disbursements'
      path: '/disbursements'
      fullPath: '/admin/grants/$grantId/disbursements'
      preLoaderRoute: typeof AdminGrantsGrantIdDisbursementsRouteImport
      parentRoute: typeof AdminGrantsGrantIdRoute
    }
  }
}

interface ExpenseRouteChildren {
  ExpenseExpenseIdRoute: typeof ExpenseExpenseIdRoute
  ExpenseIndexRoute: typeof ExpenseIndexRoute
}

const ExpenseRouteChildren: ExpenseRouteChildren = {
  ExpenseExpenseIdRoute: ExpenseExpenseIdRoute,
  ExpenseIndexRoute: ExpenseIndexRoute,
}

const ExpenseRouteWithChildren =
  ExpenseRoute._addFileChildren(ExpenseRouteChildren)

interface GrantRouteChildren {
  GrantGrantIdRoute: typeof GrantGrantIdRoute
  GrantIndexRoute: typeof GrantIndexRoute
}

const GrantRouteChildren: GrantRouteChildren = {
  GrantGrantIdRoute: GrantGrantIdRoute,
  GrantIndexRoute: GrantIndexRoute,
}

const GrantRouteWithChildren = GrantRoute._addFileChildren(GrantRouteChildren)

interface AdminExpensesRouteChildren {
  AdminExpensesExpenseIdRoute: typeof AdminExpensesExpenseIdRoute
  AdminExpensesIndexRoute: typeof AdminExpensesIndexRoute
}

const AdminExpensesRouteChildren: AdminExpensesRouteChildren = {
  AdminExpensesExpenseIdRoute: AdminExpensesExpenseIdRoute,
  AdminExpensesIndexRoute: AdminExpensesIndexRoute,
}

const AdminExpensesRouteWithChildren = AdminExpensesRoute._addFileChildren(
  AdminExpensesRouteChildren,
)

interface AdminGrantsGrantIdRouteChildren {
  AdminGrantsGrantIdDisbursementsRoute: typeof AdminGrantsGrantIdDisbursementsRoute
  AdminGrantsGrantIdFundsUsageRoute: typeof AdminGrantsGrantIdFundsUsageRoute
  AdminGrantsGrantIdMilestonesRoute: typeof AdminGrantsGrantIdMilestonesRoute
  AdminGrantsGrantIdIndexRoute: typeof AdminGrantsGrantIdIndexRoute
}

const AdminGrantsGrantIdRouteChildren: AdminGrantsGrantIdRouteChildren = {
  AdminGrantsGrantIdDisbursementsRoute: AdminGrantsGrantIdDisbursementsRoute,
  AdminGrantsGrantIdFundsUsageRoute: AdminGrantsGrantIdFundsUsageRoute,
  AdminGrantsGrantIdMilestonesRoute: AdminGrantsGrantIdMilestonesRoute,
  AdminGrantsGrantIdIndexRoute: AdminGrantsGrantIdIndexRoute,
}

const AdminGrantsGrantIdRouteWithChildren =
  AdminGrantsGrantIdRoute._addFileChildren(AdminGrantsGrantIdRouteChildren)

interface AdminGrantsRouteChildren {
  AdminGrantsGrantIdRoute: typeof AdminGrantsGrantIdRouteWithChildren
  AdminGrantsIndexRoute: typeof AdminGrantsIndexRoute
}

const AdminGrantsRouteChildren: AdminGrantsRouteChildren = {
  AdminGrantsGrantIdRoute: AdminGrantsGrantIdRouteWithChildren,
  AdminGrantsIndexRoute: AdminGrantsIndexRoute,
}

const AdminGrantsRouteWithChildren = AdminGrantsRoute._addFileChildren(
  AdminGrantsRouteChildren,
)

interface AdminRouteChildren {
  Admin_layoutRoute: typeof Admin_layoutRoute
  AdminAddAdminRoute: typeof AdminAddAdminRoute
  AdminAddAssetRoute: typeof AdminAddAssetRoute
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminBudgetsRoute: typeof AdminBudgetsRoute
  AdminExpensesRoute: typeof AdminExpensesRouteWithChildren
  AdminGrantsRoute: typeof AdminGrantsRouteWithChildren
  AdminOrganizationRoute: typeof AdminOrganizationRoute
  AdminTransfersRoute: typeof AdminTransfersRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  Admin_layoutRoute: Admin_layoutRoute,
  AdminAddAdminRoute: AdminAddAdminRoute,
  AdminAddAssetRoute: AdminAddAssetRoute,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminBudgetsRoute: AdminBudgetsRoute,
  AdminExpensesRoute: AdminExpensesRouteWithChildren,
  AdminGrantsRoute: AdminGrantsRouteWithChildren,
  AdminOrganizationRoute: AdminOrganizationRoute,
  AdminTransfersRoute: AdminTransfersRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  ExpenseRoute: ExpenseRouteWithChildren,
  GrantRoute: GrantRouteWithChildren,
  LoginRoute: LoginRoute,
  TransfersRoute: TransfersRoute,
  AdminRoute: AdminRouteWithChildren,
  TransferTransferIdRoute: TransferTransferIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
